//////////////////////////////////////////////////////////////////////////
// This file belongs to qOldFox.                                        //
// Copyright (C) 2012 Ashok Shankar Das ashok.s.das@gmail.com           //
// Released under GNU GPL-V2 licence.                                   //
// for details of licence please see the copying file                   //
// or visit http://www.gnu.org and get a copy of GNU GPL-V2 licence     //
// This file is automatically generated by QtCreator.                   //
//////////////////////////////////////////////////////////////////////////
#include <QtGui/QApplication>
#include "dialog.h"

int main(int argc, char *argv[])
{
    QApplication a(argc, argv);
    Dialog w;
    w.show();

    return a.exec();
}
